// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
// Creator for attribute: generic device type, singleton.
#define CREATOR_GENERIC_DEVICE_TYPE_SINGLETON 0xB000
#define NVM3KEY_GENERIC_DEVICE_TYPE_SINGLETON ( NVM3KEY_DOMAIN_ZIGBEE | 0xB000 )
// Creator for attribute: physical environment, singleton.
#define CREATOR_PHYSICAL_ENVIRONMENT_SINGLETON 0xB001
#define NVM3KEY_PHYSICAL_ENVIRONMENT_SINGLETON ( NVM3KEY_DOMAIN_ZIGBEE | 0xB001 )


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t  tokType_generic_device_type;
typedef uint8_t  tokType_physical_environment;
#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(GENERIC_DEVICE_TYPE_SINGLETON, tokType_generic_device_type, 0)
DEFINE_BASIC_TOKEN(PHYSICAL_ENVIRONMENT_SINGLETON, tokType_physical_environment, 0x00)
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
  uint8_t ptr[1]; \
  halCommonGetToken((tokType_generic_device_type *)ptr, TOKEN_GENERIC_DEVICE_TYPE_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_GENERIC_DEVICE_TYPE_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE); \
  halCommonGetToken((tokType_physical_environment *)ptr, TOKEN_PHYSICAL_ENVIRONMENT_SINGLETON); \
  emberAfWriteServerAttribute(1, ZCL_BASIC_CLUSTER_ID, ZCL_PHYSICAL_ENVIRONMENT_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE); \
} while(false)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
  uint8_t allZeroData[1]; \
  MEMSET(allZeroData, 0, 1); \
  if ( data == NULL ) data = allZeroData; \
  if ( clusterId == 0x00 ) { \
    if ( metadata->attributeId == 0x0009 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_GENERIC_DEVICE_TYPE_SINGLETON, data); \
    if ( metadata->attributeId == 0x0011 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
      halCommonSetToken(TOKEN_PHYSICAL_ENVIRONMENT_SINGLETON, data); \
  }\
} while(false)


